wandb_version: 1

num_epochs:
  desc: null
  value: 2500
batch_size:
  desc: null
  value: 14
learning_rate:
  desc: null
  value: 0.002
patch_size:
  desc: null
  value:
  - 96
  - 96
  - 96
patches_filter:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.9.2
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696517476.378325
    t:
      1:
      - 1
      - 41
      - 48
      - 55
      3:
      - 16
      - 23
      4: 3.9.2
      5: 0.15.8
      8:
      - 5
