wandb_version: 1

num_epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 0.001
validation_interval:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.9.2
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693222422.97293
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.9.2
      5: 0.15.8
      8:
      - 5
